# Generated by Django 5.1.6 on 2025-03-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fobi", "0016_alter_formelement_id_alter_formelemententry_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100)),
                ("valor", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("costo", models.CharField(max_length=100)),
                ("requisitos", models.TextField()),
                ("fechaInicio", models.DateTimeField(verbose_name="Fecha de inicio")),
                (
                    "fechaFin",
                    models.DateTimeField(verbose_name="Fecha de finalización"),
                ),
                (
                    "fechaApertura",
                    models.DateTimeField(verbose_name="Fecha de apertura"),
                ),
                ("fechaCierre", models.DateTimeField(verbose_name="Fecha de cierre")),
                ("fechaCreacion", models.DateTimeField(auto_now=True)),
                (
                    "cantidadTitulares",
                    models.PositiveIntegerField(verbose_name="Cantidad de Titulares"),
                ),
                (
                    "cantidadSuplentes",
                    models.PositiveIntegerField(verbose_name="Cantidad de Suplentes"),
                ),
                (
                    "nombreContacto",
                    models.CharField(max_length=100, verbose_name="Nombre de contacto"),
                ),
                (
                    "emailContacto",
                    models.CharField(max_length=300, verbose_name="Email de contacto"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Activo"),
                            ("I", "Inactivo"),
                            ("F", "Finalizado"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                (
                    "formDinamico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fobi.formentry",
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscripcion.lugar",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscripcion.tipoactividad",
                        verbose_name="Tipo de actividad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscripcionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cedula", models.CharField(max_length=30, verbose_name="Cédula")),
                ("celular", models.CharField(max_length=30)),
                ("mail", models.EmailField(max_length=254)),
                ("datos", models.TextField(blank=True, null=True)),
                (
                    "fechaInscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inscripción"
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscripcion.actividad",
                    ),
                ),
            ],
        ),
    ]
